services:
  - type: web
    name: eduportal
    runtime: node
    plan: starter
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm run db:push && npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: eduportal-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        value: file:/data/prod.db
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        sync: false
